* ---------------------------------------------
		* Generated by D2GEN Compiler

		* ---------------------------------------------
			ORG 	$1000
		START: 			;= First instruction
		
		; Loaded from : io.dgen
*--------------------------------------
* math.dgen - Custom math functions
* -------------------------------------


function_add:
	; Input d0 = a, d1 = b
	; Output d0 = a + b
	add.l d1,d0
	rts
	

function_mul:
	; Input d0 = a, d1 = b
	; Output d0 = a * b
	muls.w d1, d0
	rts


		; Loaded from : math.dgen
_main:
        link    a6,#0
 		        move.l  #42,d0
        unlk    a6
        rts
SIMHALT		; Halt simulator
		END		START		; End of program
		